### ISSUE TITLE
Notifications Doc

### ISSUE THREAD

**Issue by dbendy** [drone/docs#173]
For a drone notification, is it valid to specify a branch and other conditions?  For example:

```
notify:
  slack:
    channel: foo
    when:
      event: tag
      success: true
      branch: master
```

None of the examples shown on the [notifications page](http://readme.drone.io/usage/notify/) have all of those conditions.  While testing with those conditions, something seems to be broken but I am having a hard time pinning it down.
