### ISSUE TITLE
Plugin: note special PLUGIN_NAME env var

### ISSUE THREAD

**Issue by tonglil** [drone/docs#214]
It seems like `PLUGIN_NAME` is a special env var that cannot be set via a plugin's config:
```yaml
pipeline:
  step:
    image: my/image
    name: xyz
```

`PLUGIN_NAME` is not found.

I think we should document this. Should I add it to [plugin guidelines](https://github.com/drone/docs/blob/master/content/plugin/pipeline/plugin_guidelines.md)?
