### ISSUE TITLE
document difference between secrets and registry credentials

### ISSUE THREAD

**Issue by bradrydzewski** [drone/docs#231]
> what is the difference between registry and secret tab in the user interface

Registry credentials are for downloading private docker images defined in the yaml, for example:

```
pipeline:
  build:
    image: grc.io/golang  # private
    commands:
      - go build
      - go test
  deploy:
    image: grc.io/deployer # private
    to: production
    server: 1.2.3.4
    secrets: [ ssh_key ]
```

In the above example, authentication is required to pull the gcr.io images. Registry credentials, however, are only used by drone agent and are never exposed to your pipeline environment, build steps, plugins, etc.

Secrets, on the other hand, are private parameters passed the plugins. The docker plugin is a plugin, so it does not have access to your registry credentials.
