### ISSUE TITLE
Improve Gitea integration doc

### ISSUE THREAD

**Issue by scls19fr** [drone/docs#263]
Hello,

A tutorial to help to integrate drone with gitea will be great.
I've only found http://docs.drone.io/install-for-gitea/
which is a bit light for Docker beginners (and also gitea / drone beginner)
Same as https://github.com/go-gitea/docs/issues/159

Kind regards

**Comment by bradrydzewski** [comment]
I am open to improving the documentation, but would like some more actionable feedback. What information is missing that we should include? The gitea and gogs integration only requires setting a single parameter, which is why the documentation is so simple.

```
GITEA_URL=https://gitea.company.com
```

**Comment by scls19fr** [comment]
Thanks @bradrydzewski for your quick answer.

I think what is missing for a Docker beginner (like me) is a kind of tutorial from a Docker OS install (RancherOS, CoreOS...) to a running source code repository manager (Gitea) with continuous integration (Drone.io) and a sample project with unit tests (Python, Julia).
(It could also tackle code coverage)

But I will try and ask in forum if I can't find solution by myself.

Commands like 

    $ docker-compose up -d

should for example be given (which is not evident for Docker beginners)

Installing `docker-compose` on RancherOS is for example not very easy (this is out of the scope but that's a first problem)

This kind of prerequisite should explicitly be written (with minimum version required).

I'm very pleased to know that only setting

    GITEA_URL=https://gitea.company.com

is required but I think that

      - DRONE_SERVER=ws://drone-server:8000/ws/broker

should also be set correctly (is drone-server my RancherOS IP ?)

I have no idea (for now) how DRONE_SECRET should be passed in

      - DRONE_SECRET=${DRONE_SECRET}

https://stackoverflow.com/questions/34322631/how-to-pass-arguments-within-docker-compose
could be an answer to that question.

I understand that it's hard for developers of such a great tool to understand that DevOps beginners (like I'm) need to learn a lot before being able to have such a tool ready.

**Comment by scls19fr** [comment]
My Gitea web server is available using http://192.168.1.5:3000

Here is my `docker-compose.yml`

```
$ cat docker-compose.yml
version: '2'

services:
  drone-server:
    image: drone/drone:0.7
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=${DRONE_HOST}
      - DRONE_GITEA=true
      - DRONE_GITEA_URL=http://192.168.1.5:3000
      - DRONE_SECRET=${DRONE_SECRET}

  drone-agent:
    image: drone/drone:0.7
    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=ws://drone-server:8000/ws/broker
      - DRONE_SECRET=${DRONE_SECRET}
```

and my env variable was set using:

```
export DRONE_HOST=192.168.1.5
export DRONE_SECRET=.....
```

I build containers using:

```
$ docker-compose up -d
```

but I haven't been able to connect to Drone using web interface

```
$ docker-compose ps
         Name               Command      State              Ports
---------------------------------------------------------------------------
droneci_drone-agent_1    /drone agent    Up       443/tcp, 80/tcp, 8000/tcp
droneci_drone-server_1   /drone server   Exit 1
```

Any idea?

I will submit a PR to help to improve doc for other people facing similar problem.

Thanks

**Comment by scls19fr** [comment]
Changing for

```
version: '2'

services:
  drone-server:
    image: drone/drone:0.7
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=${DRONE_HOST}
      - DRONE_GITEA=true
      - DRONE_GITEA_URL=http://192.168.1.5:3000
      - DRONE_SECRET=${DRONE_SECRET}

  drone-agent:
    image: drone/drone:0.7
    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
-      - DRONE_SERVER=ws://drone-server:8000/ws/broker
+      - DRONE_SERVER=ws://192.168.1.5:8000/ws/broker
      - DRONE_SECRET=${DRONE_SECRET}
```

and

```
 docker-compose ps
         Name               Command      State             Ports
--------------------------------------------------------------------------
droneci_drone-agent_1    /drone agent    Up      443/tcp, 80/tcp, 8000/tcp
droneci_drone-server_1   /drone server   Up      443/tcp, 80/tcp, 8000/tcp
```

but I still don't see web interface
