### ISSUE TITLE
RFC: Plugins defined in JSON Schema

### ISSUE THREAD

**Issue by donny-dont** [drone/docs#367]
I propose that plugin documentation is written in JSON schema and then that is used to create the documentation for plugins.

# Why JSON Schema

1. JSON schema is a well supported format for defining data structures
2. The parameters to a plugin end up being treated like a data structure configuration
3. This opens up the ability for tools to potentially produce pipelines

# What would a schema look like for a plugin?

Here's an example for NPM written in YAML. The format is an extended version of JSON schema with just some additional fields for different Drone bits.

```
name: NPM
description: |
  The NPM plugin can be used to publish JavaScript libraries to both the public
  NPM registry as well as on-prem registries.
author: Don Olmstead
image: plugins/npm
repository: https://github.com/drone-plugins/drone-npm

properties:
  username:
    type: string
    description: >
      The username of the account to publish to the registry with.
    secrets:
      - npm_username

  password:
    type: string
    description: >
      The password for the account to publish to the registry with.
    secrets:
      - npm_password

  token:
    type: string
    description: >
      The token for the account to publish to the registry with.
    secrets:
      - npm_token

  email:
    type: string
    description: >
      The e-mail address associated with the account to publish with.
    secrets:
      - npm_email

  registry:
    type: string
    description: >
      The registry URL to publish to.
    default: https://registry.npmjs.org
    secrets:
      - npm_registry

  folder:
    type: string
    description: >
      The folder, relative to the workspace, containing the library.

      This can be specified when publishing different packages in a
      mono-repo.
    default: /

  tag:
    type: string
    default: latest
    description: >
      The NPM tag to publish with.

      This can be used for pre-release versions of libraries. See
      [label](https://docs.npmjs.com/getting-started/using-tags)
      documentation for further information on how to use tags when
      publishing.

  access:
    type: string
    enum:
      - public
      - restricted
    default: public
    description: >
      The access for a scoped NPM package.

# Area to make examples
examples:
  description: Publishing to the public NPM registry
  values:
    name: publish
    username: octocat
    email: octocat@octocat.com
    secrets:
      - npm_password
```

One thing that is more complicated is when a plugin supports different modes. As an example the s3-cache plugin can rebuild, restore, or flush. JSON schema supports inheritance so this could be done like this.

_NOTE this is not a full implementation just enough to make the point_

```
name: s3-cache
image: plugins/s3-cache

definitions:
  common:
    properties:
      access_key:
        type: string

  restore:
    allOf:
      - $ref: common
    properties:
      restore:
        type: boolean

  rebuild:
    allOf:
      - $ref: common
    required:
      - mount
    properties:
      mount:
        type: array
        items:
          type: string
```

**Comment by donny-dont** [comment]
One thing of note is that maybe even the NPM plugin could be split up with whether or not its username password or deploy token. This is more complicated but maybe it makes things more explicit.

**Comment by bradrydzewski** [comment]
great idea ... I remember wanted autogeneration a while back, but I hesitated because I didn't want to invent and maintain my own format. So the fact that we can use something standard is a huge win.

in terms of secrets, this is actually going to be even more simple in 0.9:

```
kind: pipeline
name: default

steps:
- name: slack
  image: plugins/slack
```

**Comment by donny-dont** [comment]
@bradrydzewski is 0.9 going back to the implicit secrets? Either way they just need to be documented period so people know about them. That's why there's that additional `secrets` value. I'd probably prefer it to be a single value but I know some plugins don't have that.

**Comment by tboerger** [comment]
I like this idea, that also drops the plugin index inconsistent styles from time to time

**Comment by bradrydzewski** [comment]
I would describe them as explicit, since you need to use the `from_secret` parameter. For example:

without secrets:

```
steps:
- name: slack
  image: plugins/slack
  settings:
    room: general
    webhook: https://...
```

with secrets:

```
steps:
- name: slack
  image: plugins/slack
  settings:
    room: general
    webhook:
      from_secret: <name of secret>
```

I think it ends up being way more clear than what we have today, which is `secrets: [ username, password ]`. This approach leads to a ton of support requests because people don't know that they need to follow plugin-defined naming conventions when passing secrets.

**Comment by tboerger** [comment]
Ah and don't forget a definition for a default value :)

**Comment by bradrydzewski** [comment]
also

- docker repository url
- supported platforms, where a platform consists of os, architecture, version, variant (all strings)

**Comment by donny-dont** [comment]
@tboerger those are there. Actually JSON schema added them. There are also enums.

If we were to go this route another drone "project" maybe more of a community thing would be something that could write out `.drone.yml` files. You could kinda have a cookbook setup where you have like a `golang` wizard. You can kinda see how you could make a kinda hyper schema for that.

```
name: golang-deps

config:
  name:
    description: The name of the build step
    default: deps
  version:
    description: The Go version to use
    default: 1.11

step:
  name: ${name}
  image: golang:${version}
  pull: true
  steps:
    - go get -u github.com/golang/dep/cmd/go
    - dep ensure
```

**Comment by donny-dont** [comment]
Hmmm so thinking more we often have multiple sort of paths to things

```
definitions:
  user:
    description:
      For authentication the NPM plugin can use a username and password.
    properties:
      username:
      password:

  token:
    description:
      NPM Enterprise instances can authenticate using a deploy token.
    properties:
      token:
      registry:

  npm:
    oneOf:
      - $ref: user
      - $ref: token
```
