### ISSUE TITLE
Typo: "pull-request"

### ISSUE THREAD

**Issue by microtherion** [drone/docs#390]
https://docs.drone.io/user-guide/pipeline/steps/ spells the same event two different ways:

```
  when:
    event:
    - pull_request

when:
  event:
  - push
  - pull-request
```
