### ISSUE TITLE
Filter plugins by category

### ISSUE THREAD

**Issue by bradrydzewski** [drone/docs#48]
We have a list of all plugins in our documentation:
http://readme.drone.io/plugins/

Hugo gives us the ability to filter a list by tag or category. This means we should be able to display a list of all plugins that are _deployment_ plugins:

```toml
tags = ["aws", "codedeploy"]
categories = "deploy"
```

Or we could filter by tag and display all _aws_ plugins. When viewing a single plugin we could even suggest other related plugins.
