### ISSUE TITLE
`auth_config` docs are incomplete

### ISSUE THREAD

**Issue by tboerger** [drone/docs#73]
At http://readme.drone.io/usage/build_test/#images:fb92aa3346185c57f15afda861d465a3 we are mentioning `auth_config`, it looks like this is incomplete as docker requires username, password and email to authenticate correctly. So please add this as an example:

```
build:
  image: foo/bar
  auth_config:
    username: octocat
    password: password
    email: octocat@github.com
```
